project:
  type: website

website:
  title: "Diego Ramos Álvarez"
  navbar:
    left:
      - href: index.qmd
        text: Home
    tools: 
      - icon: github
        url: https://github.com/DJRamosA


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

